apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgy-app
  template:
    metadata:
      labels:
        app: budgy-app
    spec:
      containers:
      - name: budgy-app
        image: sam2236/demoapp:v1
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password
        # - name: DATABASE_URL
        #   value: postgresql://Budgy:Budgy_password@postgresql/Budgy_production
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"